In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]
print(mylist)
type(mylist)

[1, 2, 3]


list

In [ ]:
arr = np.array(mylist)
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [ ]:
mylist_mul=mylist*2
print(mylist_mul)

[1, 2, 3, 1, 2, 3]


In [ ]:
arr_mul=arr*2
arr_mul

array([2, 4, 6])

In [ ]:
arr.ndim

1

In [ ]:
myTuple=(1,2,3)
print(myTuple)
type(myTuple)

(1, 2, 3)


tuple

In [ ]:
arrTuple=np.array(myTuple)
print(arrTuple)
type(arrTuple)

[1 2 3]


numpy.ndarray

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
list1=[1,2,3]
list2=[4,5,6,]
arr3=np.array([list1,list2])
print(arr3)
arr3.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
arr3.itemsize

4

In [ ]:
arr3.size

6

In [ ]:
arr3.dtype

dtype('int32')

In [ ]:
arr3.shape

(2, 3)

In [ ]:
arr3.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr3.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
print(arr2[1])

[1 2 3]


In [ ]:
print(arr2[1,1])

5


In [ ]:
#iterate
arr2[0:,2]

array([3, 6])

In [ ]:
n_arr = np.array([(1,2),(3,4),(5,6),(7,8)])
print(n_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(n_arr[0:,1])

[2 4 6 8]


In [ ]:
print(n_arr[0:2,1])

[2 4]


In [ ]:
print(n_arr[1:3,1])

[4 6]


In [ ]:
print(n_arr[1:3,0:2])

[[3 4]
 [5 6]]


In [ ]:
#Evenly spaced number
e_val = np.linspace(1,3,20)
print(e_val)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


In [ ]:
print(arr)
print(arr.min())
print(arr.max())

[1 2 3]
1
3


In [ ]:
arr.sum()

6

In [ ]:
print(arr2)
print("sum of all the value",arr2.sum())
print("sum of all row value",arr2.sum(axis=1))
print("sum of all column value",arr2.sum(axis=0))

[[1 2 3]
 [4 5 6]]
sum of all the value 21
sum of all row value [ 6 15]
sum of all column value [5 7 9]


In [ ]:
arrsqure=arr**2
print(arrsqure)

[1 4 9]


In [ ]:
np.sqrt(arrsqure)

array([1., 2., 3.])

In [ ]:
array1=np.array([(1,2,3),(4,5,6)])
array2=np.array([(1,2,3),(4,5,6)])
addarray=array1+array2
print(addarray)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((array1,array2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])