In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn

In [6]:
df = pd.read_csv("C:/Users/Anmol/Desktop/data science/insurance_data.csv")

In [13]:
df.head()
df.shape

(27, 2)

In [8]:
x=df.age.values
y=df.bought_insurance.values

In [9]:
#train test split
from sklearn.model_selection import train_test_split

In [11]:
#split it to 10% testing and remaining training
X_train, X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.1)

In [12]:
X_test

array([18, 27, 45], dtype=int64)

In [14]:
Y_test

array([0, 0, 1], dtype=int64)

In [15]:
X_train

array([61, 18, 26, 19, 28, 47, 23, 25, 55, 22, 46, 58, 55, 25, 52, 56, 49,
       29, 40, 21, 62, 50, 54, 60], dtype=int64)

In [16]:
Y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1], dtype=int64)

# K Fold Cross Validation

In [19]:
from sklearn.model_selection import KFold
import numpy as np
kf = KFold(10)
for train, test in kf.split(x):
    print("train: %s test:%s "%(x[train],x[test]))

train: [52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test:[22 25 47] 
train: [22 25 47 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test:[52 46 56] 
train: [22 25 47 52 46 56 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test:[55 60 62] 
train: [22 25 47 52 46 56 55 60 62 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test:[61 18 28] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 55 25 58 19 18 21 26 40 45 50 54 23] test:[27 29 49] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 19 18 21 26 40 45 50 54 23] test:[55 25 58] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 26 40 45 50 54 23] test:[19 18 21] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 45 50 54
 23] test:[26 40] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 54
 23] test:[45 50] 
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45
 50] test:[54 23] 
