In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [50]:
dataset=pd.read_excel("C:/Users/Anmol/Desktop/data science/stark_data.xlsx")

In [51]:
dataset

Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0
5     Sansa  24.0  Female         1

In [52]:
dataset.shape

(6, 4)

In [53]:
X = dataset.iloc[:,:-1].values
X

array([['Eddard', 52.0, 'Male'],
       ['John', 27.0, 'Male'],
       ['Arya', 21.0, 'Female'],
       ['Bran', 19.0, 'Male'],
       ['Robb', nan, 'Male'],
       ['Sansa', 24.0, 'Female']], dtype=object)

In [54]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean',axis = 0)
imputer.fit(X[:,1:2])
X[:,1:2] = imputer.transform(X[:,1:2])
X[:,1:2]
X

array([['Eddard', 52.0, 'Male'],
       ['John', 27.0, 'Male'],
       ['Arya', 21.0, 'Female'],
       ['Bran', 19.0, 'Male'],
       ['Robb', 28.6, 'Male'],
       ['Sansa', 24.0, 'Female']], dtype=object)

In [55]:
X_gender = dataset.iloc[:,2].values
X_gender

array(['Male', 'Male', 'Female', 'Male', 'Male', 'Female'], dtype=object)

In [56]:
X_dummy1 = pd.get_dummies(X_gender)
X_dummy1

Female  Male
0       0     1
1       0     1
2       1     0
3       0     1
4       0     1
5       1     0

In [57]:
X_dummy2 = pd.get_dummies(X_gender,drop_first=True)
X_dummy2

Male
0     1
1     1
2     0
3     1
4     1
5     0

In [58]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,2]=labelencoder_X.fit_transform(X[:,2])
X[:,2]
X

array([['Eddard', 52.0, 1],
       ['John', 27.0, 1],
       ['Arya', 21.0, 0],
       ['Bran', 19.0, 1],
       ['Robb', 28.6, 1],
       ['Sansa', 24.0, 0]], dtype=object)

In [59]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([2, 3, 0, 1, 4, 5], dtype=object)

In [60]:
X

array([[2, 52.0, 1],
       [3, 27.0, 1],
       [0, 21.0, 0],
       [1, 19.0, 1],
       [4, 28.6, 1],
       [5, 24.0, 0]], dtype=object)

In [61]:
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\Anmol\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])