In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [7]:
dataset=pd.read_excel("C:/Users/Anmol/Desktop/data science/stark_data.xlsx")

In [8]:
dataset.head

<bound method NDFrame.head of   Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0
5     Sansa  24.0  Female         1>

In [9]:
X = dataset.iloc[:,:-1].values
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean',axis = 0)
imputer.fit(X[:,1:2])
X[:,1:2] = imputer.transform(X[:,1:2])
X[:,1:2]
X

C:\Users\Anmol\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([['Eddard', 52.0, 'Male'],
       ['John', 27.0, 'Male'],
       ['Arya', 21.0, 'Female'],
       ['Bran', 19.0, 'Male'],
       ['Robb', 28.6, 'Male'],
       ['Sansa', 24.0, 'Female']], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,2]=labelencoder_X.fit_transform(X[:,2])
X[:,2]
X

array([['Eddard', 52.0, 1],
       ['John', 27.0, 1],
       ['Arya', 21.0, 0],
       ['Bran', 19.0, 1],
       ['Robb', 28.6, 1],
       ['Sansa', 24.0, 0]], dtype=object)

In [12]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([2, 3, 0, 1, 4, 5], dtype=object)

In [13]:
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\Anmol\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Anmol\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])

In [14]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
standardScalerX = StandardScaler()
std_X = standardScalerX.fit_transform(X)

In [15]:
std_X

array([[-4.47213595e-01, -4.47213595e-01,  2.23606798e+00,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
         2.13434010e+00,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
         2.23606798e+00, -4.47213595e-01, -4.47213595e-01,
        -1.45937784e-01,  7.07106781e-01],
       [ 2.23606798e+00, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -6.93204476e-01, -1.41421356e+00],
       [-4.47213595e-01,  2.23606798e+00, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -8.75626707e-01,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01,  2.23606798e+00, -4.47213595e-01,
         3.24046977e-16,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01,  2.23606798e+00,
        -4.19571130e-01, -1.41421356e+00]])

In [16]:
#feature scaling with min max
from sklearn.preprocessing import MinMaxScaler
MinMaxScalerX = MinMaxScaler()
MN_X=MinMaxScalerX.fit_transform(X)

In [17]:
MN_X

array([[0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.24242424, 1.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.06060606, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.29090909, 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.15151515, 0.        ]])